language: go
addons:
  apt:
    packages:
      - nginx
      - tzdata
      - cpanminus
before_install:
  - cpanm --local-lib=~/perl5 --quiet local::lib
  - eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
  - cpanm --local-lib=~/perl5 --quiet --notest Test::Nginx::Socket
  - echo "const VERSION = \"${TRAVIS_TAG}\"" >> version.go
script:
  - go build -o ip2geo
  - ./ip2geo
  - TEST_NGINX_IP2GEO_DIR=$PWD prove t/nginx_geo.t
  - ./ip2geo -lang en -nobase64
  - TEST_NGINX_IP2GEO_DIR=$PWD prove t/nginx_geo.t
  - ./ip2geo -ipver 6
  - TEST_NGINX_IP2GEO_DIR=$PWD prove t/nginx_geo_ipv6.t
  - ./ip2geo -ipver 6 -lang en -nobase64
  - TEST_NGINX_IP2GEO_DIR=$PWD prove t/nginx_geo_ipv6.t
after_success:
  - GOOS=darwin go build -o ip2geo-mac
  - GOOS=freebsd go build -o ip2geo-freebsd
  - GOOS=linux GOARCH=386 go build -o ip2geo-linux32
  - GOOS=linux GOARCH=amd64 go build -o ip2geo-linux64
  - GOOS=linux GOARCH=arm go build -o ip2geo-linuxARM
  - GOOS=openbsd go build -o ip2geo-openbsd
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: azRgS7b9ee9XwzTGeSj8p7NqAFI7hZk3RfJGnZg2ji/dtihhuPo3RA5c3VFUAGTTpcU0h4xBCmJ8S1Li3P8nI7PNA85Y83ul6o0gqroOBAgiuIh6PlHRCg13zG3g3PMbFOHAtKIDcJl05cXJSkJUnK72ShGd5dXG/yC0deFf9oizW1hSq9VXPn36gGWMnT4NOBpiAXESdwEfFY3/6rVQu5EWLjqS3jmdB2KtOBQbkeKRYiaOMdw6nP3VhuRbPIF1tWVy8JvP3+9aV8R7SfRAbaHqECXwn/8qvW/rrYAYpovxtALcGLqoPNYcC/lCsw3Vf/QtzELiIeEqw3Ho5qvYwPLe0the7bnQa7CoDbNO4gxbF14lAEyIbq5Z566bh30m0cXBm3EW8LZHJ6jA/vtsIQIEqFcM0/W/Xr62torAFzvlrEmG2nDiOnGfUfJivhdLKgtROfD87d957pewF/dv9HBxq5MD59QWb1K+eV6saPY+ULcqcv1xSAVc9jtIMM/cINdwoPosOQJdRYmxNjVJ4mncVzTsx8a+WRJPkBnYY1wb14O927gjwLAy12sxdKPURHu9PV7LY7IP9mUWy49yR5oKGiHDFuQYTu3a2WyfsE7vvb2H+1Th8lcf9vMXf2VvhGLBwIGJeejYTdZy8S5igGfEUnwucXoL4dxWpaX62uU=
  file:
    - ip2geo-mac
    - ip2geo-freebsd
    - ip2geo-linux32
    - ip2geo-linux64
    - ip2geo-linuxARM
    - ip2geo-openbsd
  on:
    repo: m-messiah/ip2geo
    tags: true
